dist: xenial
language: python
matrix:
  include:
    - name: Ansible devel with Python 2.7
      python: "2.7"
      env:
        - ANSIBLE=devel
    - name: Ansible devel with Python 3.5
      python: "3.5"
      env:
        - ANSIBLE=devel
    - name: Ansible devel with Python 3.6
      python: "3.6"
      env:
        - ANSIBLE=devel
    - name: Ansible devel with Python 3.7
      python: "3.7"
      env:
        - ANSIBLE=devel
    - name: Ansible 2.7 with Python 3.7
      python: "3.7"
      env:
        - ANSIBLE=stable-2.7
    - name: Ansible 2.8 with Python 3.7
      python: "3.7"
      env:
        - ANSIBLE=stable-2.8
addons:
  apt:
    packages:
      - rpm
install:
  - pip install git+https://github.com/ansible/ansible.git@${ANSIBLE}#egg=ansible
  - pip install pytest-travis-fold
  - make test-setup
  - if [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then make doc-setup; fi
script:
  - if [[ $ANSIBLE == devel ]]; then make lint sanity dist-test; fi
  - make test
  - if [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then make doc; fi
